services:
  badbank-app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
